# Welcome to Jekyll!
#

# Site settings
title: DIGITAL POSTURE
description: |
  stay inspired, 
  inspire confidence    
owner: Digital Posture # or company name

first_published: 2025 # if migrating another site, the year of your first publish
exclude: [3dimensions_copy.html]

email: digital.posture.info@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://digital-posture.com"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v4.4.1

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: digital.posture.info@gmail.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  cybersecurity:
    output: true
  digital_posture:
    output: true
    order:
      - Digital Culture and Skills
      - Digital Presence and Support
      - Digital Infrastructure and Processes
